require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/NestedGroups:
  Enabled: true
  MaxNesting: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 8

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "*.gemspec"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"
